language: java
install: true

os: linux
dist: trusty
jdk: openjdk8

before_script:
  - chmod a+x gradlew

addons:
  sonarcloud:
    organization: "jullierme-github"
    token:
      secure: $sonarcloud

script:
  - ./gradlew test
  - ./gradlew sonarqube

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - ./gradlew jacocoTestReport coveralls