language: java
install: gradle wrapper --gradle-version=5.5.1 --distribution-type=all

os: linux
dist: trusty
jdk: openjdk8

before_script:
  - chmod a+x gradlew

script:
  - ./gradlew test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/